import { Montserrat } from "next/font/google";
import "./globals.css";
import Footer from "@/app/components/main/Footer/Footer";
import Header from "@/app/components/main/Header/Header";
import { Fragment } from "react";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <Header />
        <div className="pb-[120px]">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
